package beans;

public enum Action {
    CONNECTION_OPEN,
    CONNECTION_CLOSE,
    LOGIN,
    REGISTRATION,
    CREATE_NOTIFIER,
    GET_ROOMS,
    GET_MESSAGES,
    GET_USERS,
    ADD_ROOM,
    ADD_MESSAGE,
    NOTIFY_MESSAGE,
    NOTIFY_ROOM
}