package beans;

public enum Action {
    CONNECTION_OPEN,
    CONNECTION_CLOSE,
    AUTHENTICATION,
    CREATE_NOTIFIER,
    GET_ROOMS,
    GET_MESSAGES,
    GET_USERS,
    ADD_ROOM,
    ADD_MESSAGE,
    NOTIFY
}